application: ccdjh-fuckme
version: 1
runtime: python
api_version: 1



handlers:

- url: /static
  static_dir: cm/static/css/

-  url: /admin/.*
   script: urlControl.py
   login: admin

- url: /.*
  script: urlControl.py

  
  
