application: chrysanthemumcm
version: 1
runtime: python
api_version: 1



handlers:

- url: /static
  static_dir: cm/static/

-  url: /admin/.*
   script: urlControl.py
   login: admin

- url: /.*
  script: urlControl.py

- url: /favicon.ico
  static_files: cm/static/image/favicon.ico
  upload: cm/static/image/favicon.ico
  mime_type: image/x-icon
  
